# Generated by Django 6.1 on 2026-08-24 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_profile_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_priority',
            field=models.ForeignKey(blank=True, help_text='Priority automatically assigned to tickets in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.priority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'])]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Ticket Created'), ('auto_priority_set', 'Auto-Priority Set'), ('auto_assigned', 'Auto-Assigned'), ('manually_assigned', 'Manually Assigned'), ('reassigned', 'Reassigned'), ('status_changed', 'Status Changed'), ('sla_warning', 'SLA Warning Sent'), ('escalated', 'Escalated'), ('escalated_level2', 'Escalated (Urgent — Level 2)'), ('auto_closed', 'Auto-Closed')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='Null means the action was performed by SYSTEM automation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_created', 'New Ticket Created'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_overdue', 'Ticket Overdue'), ('ticket_escalated', 'Ticket Escalated'), ('ticket_auto_closed', 'Ticket Auto-Closed')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
