# Generated by Django 6.1 on 2026-08-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_create_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.ForeignKey(blank=True, help_text='For ICT Agents: the issue category this agent specializes in. Auto-assignment prefers a matching specialist before falling back to the least-loaded agent overall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_agents', to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
